# Generated by Django 6.1 on 2026-08-26 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('internal_length_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('internal_width_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('internal_height_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_weight_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['cost'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='boxes.box')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boxes.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boxes.product')),
            ],
        ),
    ]
